[package]
name = "super_clipboard"
authors = ["SergioRibera"]
description = "GUI Application for manage history clipboard; Cli options overwrite settings"
version = "1.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true
opt-level = "z"

[dependencies]
open = "4.0.0"
log = "0.4.17"
rlsf = "0.2.1"
env_logger = "0.10.0"
iced_native = "0.9.1"
device_query = "1.1.1"
display-info = "0.4.1"
arboard = { version = "3.2", features = ["wayland-data-control"] }
clap = { version = "4.1.8", features = ["derive"] }
serde = { version = "1.0.155", features = ["derive"] }
iced = { version = "0.8.0", default-features = false, features = [
    "canvas",
    "glow",
    "image",
    "svg",
    # "default_system_font",
    "async-std",
] }
chrono = { version = "0.4.24", default-features = false, features = [
    "clock",
    "std",
    "serde",
] }
preferences = { version = "3.0.0", git = "https://github.com/SergioRibera/preferences-rs" }
