[toolchain]
channel = "stable"
profile = "default"
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "armv7-unknown-linux-gnueabihf",
]
components = ["clippy", "rustfmt"]
