name: Build and deploy

permissions:
  contents: write

env:
  APP_NAME: super_clipboard

on:
  push:
    paths-ignore:
      - ".github/workflow/*.yml"
      - "**/Makefile.toml"
      - "Cross.toml"
      - "release.toml"
      - "LICENSE"
      - "README.md"
    tags:
      - "*"

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y libxdo-dev
      - name: build release
        uses: actions-rs/cargo@v1.0.1
        with:
          args: --release
          command: build
      - name: Post Build | Prepare artifacts
        run: |
          mv target/release/${{ env.APP_NAME }} ${{ env.APP_NAME }}
          tar cvzf ${{ env.APP_NAME }}_x86_64-linux.tar.gz LICENSE ${{ env.APP_NAME }}
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APP_NAME }}_x86_64-linux.tar.gz
          prerelease: ${{ contains(github.ref_name, 'a') }}
