name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/build.yml"
      - "Cross.toml"
      - "Makefile.toml"
      - "README.md"
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Run cargo clippy -- -D warnings
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    env:
      OPENMC_ENCRYPT_KEY: ${{ secrets.OPENMC_ENCRYPT_KEY }}
      LITCRYPT_ENCRYPT_KEY: ${{ secrets.LITCRYPT_ENCRYPT_KEY }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dsherret/rust-toolchain-file@v1
      - name: Run clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          command: clippy
          args: -- -D warnings

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    env:
      OPENMC_ENCRYPT_KEY: ${{ secrets.OPENMC_ENCRYPT_KEY }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: dsherret/rust-toolchain-file@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: --all -- --check
